<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: martin
 * Date: Tue, 07 Jun 2016 20:15:51 +0000
 */

$conf['title'] = 'Wiki de YoTeLlevo';
$conf['lang'] = 'es';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
